### ISSUE TITLE
Bad layout

### ISSUE THREAD

**Issue by godfreyd** [bem-site/bem.info#212] opened 2017-10-11 18:49 UTC
<img width="1280" alt="2017-10-11 21 47 18" src="https://user-images.githubusercontent.com/6197968/31460127-04d840f4-aece-11e7-99b1-918a925d18d8.png">

**Comment by a-lexxx** [comment] 2017-10-11 18:59
It seems like duplicate of #207

**Closed by a-lexxx** 2017-10-11 18:59 UTC
